# -*- coding: utf-8 -*-
"""for,while,continue,break

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1erJRiNhHX65IP1k_TmZf5-nM1-XJgupn
"""

# Break the for loop at 'blue'
colors = ['red','green','blue','yellow']
for x in colors:
  if x == 'blue':
    break
  print(x)

# Break the while loop when x becomes 3

x = int(input('Enter the number between 6 to 12: '))

while x:
  print(x)
  x -= 1
  if x == 3:
    break

# The Else Clause
# If the loop terminates prematurely with break, the else clause won’t be executed.

colors = ['red','green','blue','yellow']
for x in colors:
  if x == 'blue':
    break
  print(x)
else:
  print('Done!')

# Break inside try.. finally Block

for x in range(5):
  try:
    print('trying...')
    break
    print('still trying')
  except:
    print('Something went wrong.')
  finally:
    print('Done!')

# in while statement

while 1:
  try:
    print('trying...')
    break
    print('still trying...')
  except:
    print('Something went wrong.')
  finally:
    print('Done!')

# Continue Statement The continue statement skips the current iteration of a loop and continues with the next iteration.
# Continue in for and while Loop

colors = ['red','green','blue','yellow']
for x in colors:
  if x == 'blue':
    continue
  print(x)

# Print values from 6 through 0 while skipping odd numbers.

x = 6
while x:
  x -= 1
  if x % 2 != 0:
    continue
  print(x)

# in a for Statement

for x in range(2):
  try:
    print('trying...')
    continue
    print('still trying...')
  except:
    print('Something went wrong')
  finally:
    print('Done!')
print('Loop ended.')

from prompt_toolkit.completion.filesystem import ExecutableCompleter
# in a while statement

x = 2
while x:
  try:
    print('trying...')
    x -= 1
    continue
    print('Still trying...')
  except:
    print('Something went wrong.')
  finally:
    print('Done!')
print('Loop ended')

